//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RBUkraine.DAL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Images {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Images() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RBUkraine.DAL.Images", typeof(Images).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4gIcSUNDX1BST0ZJTEUAAQEAAAIMbGNtcwIQAABtbnRyUkdCIFhZWiAH3AABABkAAwApADlhY3NwQVBQTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9tYAAQAAAADTLWxjbXMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApkZXNjAAAA/AAAAF5jcHJ0AAABXAAAAAt3dHB0AAABaAAAABRia3B0AAABfAAAABRyWFlaAAABkAAAABRnWFlaAAABpAAAABRiWFlaAAABuAAAABRyVFJDAAABzAAAAEBnVFJDAAABzAAAAEBiVFJDAAABzAAAAEBkZXNjAAAAAAAAAANjMgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0ZXh0AAAAAEZCAABYWVog [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Animal1 {
            get {
                return ResourceManager.GetString("Animal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4AAQSkZJRgABAQEAZABkAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAFRAOEDAREAAhEBAxEB/8QAHAAAAQUBAQEAAAAAAAAAAAAAAgEDBAUGBwAI/8QAShAAAgECBAMFBAYHBgMHBQAAAQIDBBEABRIhMUFRBhMiYXEUMoGRByNCUqGxFWJywdHh8DM1U4KS8TRzoiRDRVRjk9IWREZ04v/EABsBAAMBAQEBAQAAAAAAAAAAAAABAwIEBQYH/8QAMREAAgICAQIEBQIHAAMAAAAAAAECEQMhMRJBBCJR8BMyYXGBobEUI5HB0eHxM0JS/9oADAMBAAIRAxEAPwDtDuG2up+G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Animal2 {
            get {
                return ResourceManager.GetString("Animal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAfQAAAH0CAYAAADL1t+KAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAIGNIUk0AAHolAACAgwAA+f8AAIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAAR7jSURBVHja7J13nF5Vtfd/a+19znnKtPRGEggJIRA6ofemoghiF7ve13vlKjYUrnjFix0Ue8WGiqIISO+99zTSQ3ovU59yztlrvX+cZyYzSYCElJkk+8tnEUKSyTOn7N9ea69CqgqPx+PxeDy7Nuwvgcfj8Xg8XtA9Ho/H4/F4Qfd4PB6Px+MF3ePxeDwejxd0j8fj8Xi8oHs8Ho/H4/GC7vF4PB6Pxwu6x+PxeDweL+gej8fj8XhB93g8Ho/H4wXd4/F4PB6PF3SPx+PxeDxe0D0ej8fj8YLu8Xg8Ho/HC7rH4/F4PB4v6B6Px+PxeF4F21yt7PbfJAEohjmkqsilQOoUalNYCuEMwKpIhRAYhSQCxwIDCxIHkAWg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharitableOrganization1 {
            get {
                return ResourceManager.GetString("CharitableOrganization1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBQVFBgUFRUZGBgYGhgdGRkaGBoiHBoaGxsaGRobGxsdIS0kGx0qIRkYJTclKi4xNDQ0GyM6PzozPi0zNDEBCwsLEA8QHRISHTMjIyQ0PDMzMzMxMzMxMzMzMTMzMzMzMzM0MzMzMzU1MTMzMzUzMzMzMzMzNDMzNTEzMzMzM//AABEIALEBHAMBIgACEQEDEQH/xAAcAAABBQEBAQAAAAAAAAAAAAAHAAECAwYFBAj/xABNEAACAAQDBAUHBwkGBAcAAAABAgADESEEEjEFBkFRBxMiYXE0UoGRobGzFDJCYnJzshYjU3SCk8HC0iUzQ2OS0RUkouEXNVSDo8Pw/8QAGQEBAAMBAQAAAAAAAAAAAAAAAAECAwQF/8QAJxEAAgICAgIBBAIDAAAAAAAAAAECEQMxBBIhMkETIlGBQlIUYXH/2gAMAwEAAhEDEQA/AC4qmosYsdgRQGsOZgIoOMVqhBqd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharitableOrganization2 {
            get {
                return ResourceManager.GetString("CharitableOrganization2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAQEBAICAgECAgEEBQkHBQMEBgQDAxQUBgsJBhQUFAUIBRQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/2wBDAQQFBAECAgYIBxQUFAcEFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/2wBDAgICAgEBARQEFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wgARCASdBJ0DABEAAREBAhEC/8QAGwABAAIDAQEAAAAAAAAAAAAAAAUGAQMEAgf/xAAYAQEBAQEBAAAAAAAAAAAAAAAAAQMCBP/aAAwDAAABEAIQAAAB+mevyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultAnimal {
            get {
                return ResourceManager.GetString("DefaultAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAkGBwgHBgkICAgKCgkLDhcPDg0NDhwUFREXIh4jIyEeICAlKjUtJScyKCAgLj8vMjc5PDw8JC1CRkE6RjU7PDn/2wBDAQoKCg4MDhsPDxs5JiAmOTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTn/wgARCANbA1sDACIAAREBAhEB/8QAGwABAAIDAQEAAAAAAAAAAAAAAAUGAwQHAQL/xAAaAQEAAwEBAQAAAAAAAAAAAAAAAQIDBAUG/9oADAMAAAEQAhAAAAG8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HappyPaw {
            get {
                return ResourceManager.GetString("HappyPaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4AAQSkZJRgABAQEAZABkAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAEOANwDASIAAhEBAxEB/8QAHAAAAgMAAwEAAAAAAAAAAAAABQYDBAcBAggA/8QARBAAAgEDAwIFAQYEAwYEBgMAAQIDAAQRBRIhMUEGEyJRYXEHFDKBkaEjQrHwFcHhCCQzUtHTQ2OC8RYXJWJykoOiwv/EABkBAAMBAQEAAAAAAAAAAAAAAAABAgMEBf/EACMRAAICAwEBAAMBAAMAAAAAAAABAhEDITESQRMiUTIEYXH/2gAMAwEAAhEDEQA/AAkatHtCcimnw8CSM0AQqAoNMmgckYrFGo3QJlBV [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lynx {
            get {
                return ResourceManager.GetString("Lynx", resourceCulture);
            }
        }
    }
}
